### ISSUE TITLE
Hide certain elements on print

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#324]
Something like this would be valuable in the CSS, e.g. for printing the finance detail page:

```css
@media print {
  
  .bootstrap-table .search,
  /* nobody needs the twitter link on a printed document */  
  div.main footer,
  ul.nav-tabs {
    display: none;
  }
  
  /* …or any links (mostly pycroft-internal), for that matter. */  
  /* however, beware that this also hides external links! */
  a:link:after,
  a:visited:after {
    content: "" !important;
  }
}
```
