### ISSUE TITLE
Use `darker` in pre-commit hook

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#565]
To enforce consistent style, gradually moving to `black` formatting is a good idea.
To achieve that, enforcing gradual formatting via `darker` is a good option.

We can set up a pre-commit hook for it as described in the [docs](https://pypi.org/project/darker/#using-as-a-pre-commit-hook):
```yaml
-   repo: https://github.com/akaihola/darker
    rev: 1.5.0
    hooks:
    -   id: darker
```
